### ISSUE TITLE
Stealth Meter Rotating White Bar 

### ISSUE THREAD

**Issue by Mich997** [UNIFIED-CAPSTONE-IEMC/The-Fall#24]
### Expected Result

The white bar meter is supposed to deplete to when near zero and disappear when it hits zero.

### Actual Result

The white bar rotates then disappears when the white bar depletes near zero then it disappears.

### Category

- [ ] Mechanics
- [ ] Visual
- [ ] Systems
- [ ] Audio
- [ ] Text
- [ ] Suggestion

### Version / Branch / Commit

0.1.2

### Reproducability

5/5

### Priority

- [ ] Immediate
- [ ] Urgent
- [ ] High
- [ ] Medium
- [ ] Low

### Severity

- [ ] Blocking
- [ ] Major
- [ ] Minor
- [ ] Tweak
- [ ] Text

### Log files or clips

N/A

### Steps to reproduce

When the Stealth Meter decreases near 0 percent the bug will appear

**Comment by Axel918** [comment]
Fixed - Rotating behavior is no longer present in the stealth bar

Reference:
https://gyazo.com/dd211db87fb62e166ca57e3f389d4d75
