### ISSUE TITLE
Floating props

### ISSUE THREAD

**Issue by Mich997** [UNIFIED-CAPSTONE-IEMC/The-Fall#28]
### Expected Result

Assets in the bathroom (ex. Sink) are placed on the counter top

### Actual Result

Assets in the bathroom (ex. Sink) are floating above the counter top

### Category

- [ ] Mechanics
- [X] Visual
- [ ] Systems
- [ ] Audio
- [ ] Text
- [ ] Suggestion

### Version / Branch / Commit

0.1.2

### Reproducability

5/5

### Priority

- [ ] Immediate
- [ ] Urgent
- [X] High
- [ ] Medium
- [ ] Low

### Severity

- [ ] Blocking
- [ ] Major
- [X] Minor
- [ ] Tweak
- [ ] Text

### Log files or clips

https://drive.google.com/open?id=1J_FzOWaq5SzBMMdipcNp9u_0KYN4AJEV

### Steps to reproduce

1. Enter a new game
2. navigate the level and head to the bathroom

**Comment by chartimbreza** [comment]
Adjusted floating items in the restroom and bullpen (day and night)
