### ISSUE TITLE
Slight gap in the wall

### ISSUE THREAD

**Issue by Mich997** [UNIFIED-CAPSTONE-IEMC/The-Fall#33]
### Expected Result

Slight gap in the wall is not visible

### Actual Result

Slight gap in the wall is visible

### Category

- [ ] Mechanics
- [X] Visual
- [ ] Systems
- [ ] Audio
- [ ] Text
- [ ] Suggestion

### Version / Branch / Commit

0.1.2

### Reproducability

5/5

### Priority

- [ ] Immediate
- [ ] Urgent
- [ ] High
- [X] Medium
- [ ] Low

### Severity

- [ ] Blocking
- [ ] Major
- [X] Minor
- [ ] Tweak
- [ ] Text

### Log files or clips

https://drive.google.com/open?id=1KxCPR8zLmzSVin-REMPjf7A4Tzp5EZ_0

### Steps to reproduce

1. start a new game
2. accomplish objectives in office (day)
3. navigate the office (night)
4. approach the corners of rooms

**Comment by chartimbreza** [comment]
Added a lightblocker to fix the issue (day and night ver.)
