### ISSUE TITLE
Clipping Walls

### ISSUE THREAD

**Issue by Mich997** [UNIFIED-CAPSTONE-IEMC/The-Fall#36]
### Expected Result

Walls are not clipping

### Actual Result

Walls are clipping

### Category

- [ ] Mechanics
- [X] Visual
- [ ] Systems
- [ ] Audio
- [ ] Text
- [ ] Suggestion

### Version / Branch / Commit

0.1.2

### Reproducability

5/5

### Priority

- [ ] Immediate
- [ ] Urgent
- [X] High
- [ ] Medium
- [ ] Low

### Severity

- [ ] Blocking
- [ ] Major
- [X] Minor
- [ ] Tweak
- [ ] Text

### Log files or clips

https://drive.google.com/open?id=18k0r77xpqCgtgaXNItV7e8og_EexhAiF

### Steps to reproduce

1. start a new game
2. navigate to the office levels
3. head to the bathroom

**Comment by chartimbreza** [comment]
Adjusted clipping walls in restroom
